[package]
name = "Rustplorer"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33"
egui-phosphor = "0.11"
egui_nerdfonts = { path = "./egui_nerdfonts" }
whoami = "1.6"
egui_dnd = { path = "./egui_dnd" }
chrono = "0.4"
